### ISSUE TITLE
Splitting is hard

### ISSUE THREAD

**Issue by arrowgamer** [wmike1987/skillexplosion#1]
How do you even beat one level? :P Video guide?

**Comment by arrowgamer** [comment]
I was wondering if somehow the game speed is tied to the frame rate, as I've observed it running more slowly on other people's computers, which makes it a lot easier.

**Comment by wmike1987** [comment]
Yeah, the framerate right now on some games is tied to the monitor's refresh rate. There's a branch on matter.js' GitHub called timing-improvements which should help/solve this problem. Definitely looking to push that build out asap.

As for the splitting, as long as you have one unit remaining, you should get points.

**Comment by arrowgamer** [comment]
Ah, thanks for the explanation. I'm not all that good at splitting, but I think I should at least be capable of passing a single level, if this gets worked out, haha.

**Comment by wmike1987** [comment]
Once the timing branch gets pushed I'm probably gonna reset all the scores since some people's are way higher because of it. I'll look to soften the splitting game too. Thanks for the feedback.
